name: Build and Publish

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project to OpenNext package
        run: npm run package

      - name: Zip OpenNext Deployment Assets
        run: cd .open-next && zip -r ../open-next.zip . -q

      - name: Store Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opennext-build
          path: open-next.zip

  publish:
    name: Publish OpenNext package
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && github.ref_name == 'main'
    concurrency: publish

    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: opennext-build

      - name: Unzip Build Artifacts to .open-next folder
        run: unzip -q -d .open-next open-next.zip

      # Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: your-s3-bucket-name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '.open-next'
